apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: pcsmomo/kub-data-demo
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
