apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  # resource is a counter part of capacity on PersistentVolume
  resources:
    requests:
      storage: 1Gi
