# Indentation is very important here
version: '3.8'
services:
  mongodb:
    # --rm -d are default options
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    ## Using : (colon)
    #   MONGO_INITDB_ROOT_USERNAME: noah
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    ## using - (dash) and = (equals sign)
    # - MONGO_INITDB_ROOT_USERNAME=noah
    env_file:
      - ./env/mongo.env
    # All services are using the same default network, though it can be manually added
    # networks:
    #   - goals-net
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  # frontend:
volumes:
  # Named Volumes must be specified
  # Anonymous Volumes and Bind Mounts are not
  data:
  logs:
